name: Java CD

on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
          with:
            changelog_file: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}$
